export const window = {
  createtime: null,
  autosave: false,
  tb_window_layout: [],
  prodid: null,
  uitype: null,
  windowtitle: null,
  devicetype: null,
  layouttype: null,
  filter: [],
  windowname: null,
  dsname: null,
  windowwidth: null,
  windowtype: null,
  id: null,
  issystemwin: null,
  windowheight: null,
  updatetime: null
}
export const container =
  {
    containername: null,
    tb_window_element: [],
    parentid: null,
    windowid: null,
    readonly: false,
    containerdesc: null,
    showpage: false,
    loaddata: false,
    checkbox: false,
    pagesize: null,
    datasubmitrange: null,
    id: null,
    createtime: null,
    autosave: false,
    orderid: null,
    gridfilter: false,
    leaf: null,
    containertype: null,
    forcefit: false,
    levelid: null
  }
export const containerSide = [
  {
    name: 'FORM表单',
    type: 'form',
    icon: 'iconfont iconbiaodan',
    containername: null,
    tb_window_element: [],
    parentid: null,
    windowid: null,
    readonly: false,
    containerdesc: null,
    showpage: false,
    loaddata: false,
    checkbox: false,
    pagesize: null,
    datasubmitrange: null,
    id: null,
    createtime: null,
    autosave: false,
    orderid: null,
    gridfilter: false,
    leaf: null,
    containertype: 'form',
    forcefit: false,
    levelid: null,
    layoutalign: null,
    iconcls: null,
    subobjid: null,
    scrollevent: null,
    filtersql: null,
    filter: [],
    layouttype: null
  },
  {
    name: '查询表单',
    type: 'searchform',
    icon: 'iconfont iconzaitu',
    containername: null,
    tb_window_element: [],
    parentid: null,
    windowid: null,
    readonly: false,
    containerdesc: null,
    showpage: false,
    loaddata: false,
    checkbox: false,
    pagesize: null,
    datasubmitrange: null,
    id: null,
    createtime: null,
    autosave: false,
    orderid: null,
    gridfilter: false,
    leaf: null,
    containertype: 'searchform',
    forcefit: false,
    levelid: null,
    layoutalign: null,
    iconcls: null,
    subobjid: null,
    scrollevent: null,
    filtersql: null,
    filter: [],
    layouttype: null
  },
  {
    row: [],
    name: '行元素',
    type: 'row',
    containername: '行元素',
    id: null,
    icon: 'iconfont iconrow',
    parentid: null
  },
  {
    name: '表格',
    type: 'grid',
    icon: 'iconfont icongrid',
    containername: null,
    tb_window_element: [],
    parentid: null,
    windowid: null,
    readonly: false,
    containerdesc: null,
    showpage: false,
    loaddata: false,
    checkbox: false,
    pagesize: null,
    datasubmitrange: null,
    id: null,
    createtime: null,
    autosave: false,
    orderid: null,
    gridfilter: false,
    leaf: null,
    containertype: 'grid',
    forcefit: false,
    levelid: null,
    tb_tool_element: [],
    layoutalign: null,
    iconcls: null,
    subobjid: null,
    scrollevent: null,
    isShowTool: false,
    toolPosition: null,
    filtersql: null,
    filter: [],
    layouttype: null
  },
  {
    name: '工具栏',
    type: 'toolbar',
    icon: 'iconfont icontool',
    containername: null,
    tb_window_element: [],
    parentid: null,
    windowid: null,
    readonly: false,
    containerdesc: null,
    showpage: false,
    loaddata: false,
    checkbox: false,
    pagesize: null,
    datasubmitrange: null,
    id: null,
    createtime: null,
    autosave: false,
    orderid: null,
    gridfilter: false,
    leaf: null,
    containertype: 'toolbar',
    forcefit: false,
    levelid: null,
    layoutalign: null,
    iconcls: null,
    subobjid: null,
    scrollevent: null,
    filtersql: null,
    filter: [],
    layouttype: null
  },
  {
    name: 'TAB容器',
    type: 'tabpanel',
    icon: 'iconfont icontabs',
    containername: null,
    tb_window_element: [],
    parentid: null,
    windowid: null,
    readonly: false,
    containerdesc: null,
    showpage: false,
    loaddata: false,
    checkbox: false,
    pagesize: null,
    datasubmitrange: null,
    id: null,
    createtime: null,
    autosave: false,
    orderid: null,
    gridfilter: false,
    leaf: null,
    containertype: 'tabpanel',
    forcefit: false,
    levelid: null,
    layoutalign: null,
    iconcls: null,
    subobjid: null,
    scrollevent: null,
    filtersql: null,
    filter: [],
    layouttype: null
  },
  {
    name: 'CARD',
    type: 'cardpanel',
    icon: 'iconfont iconcard',
    containername: null,
    tb_window_element: [],
    parentid: null,
    windowid: null,
    readonly: false,
    containerdesc: null,
    showpage: false,
    loaddata: false,
    checkbox: false,
    pagesize: null,
    datasubmitrange: null,
    id: null,
    createtime: null,
    autosave: false,
    orderid: null,
    gridfilter: false,
    leaf: null,
    containertype: 'cardpanel',
    forcefit: false,
    levelid: null,
    layoutalign: null,
    iconcls: null,
    subobjid: null,
    scrollevent: null,
    filtersql: null,
    filter: [],
    layouttype: null
  },
  {
    name: '容器',
    type: 'container',
    icon: 'iconfont iconbiaodan',
    containername: null,
    tb_window_element: [],
    parentid: null,
    windowid: null,
    readonly: false,
    containerdesc: null,
    showpage: false,
    loaddata: false,
    checkbox: false,
    pagesize: null,
    datasubmitrange: null,
    id: null,
    createtime: null,
    autosave: false,
    orderid: null,
    gridfilter: false,
    leaf: null,
    containertype: 'container',
    forcefit: false,
    levelid: null,
    layoutalign: null,
    iconcls: null,
    subobjid: null,
    scrollevent: null,
    filtersql: null,
    filter: [],
    layouttype: null
  }
]
export const element = [
  {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: false,
    type: 'input',
    title: null,
    tb_window_inputfields: [],
    rowid: null,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: null,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: null,
    tag: null,
    mustsetfiltercon: false,
    createtime: null,
    columnid: null,
    editable: false,
    leftmargin: null,
    topmargin: null,
    tb_window_uploadfile: [],
    elementname: null,
    bottommargin: null,
    authcontroltype: null,
    astablevar: false,
    containerid: null,
    batchupdate: null,
    searchop: null,
    elementdesc: null,
    name: '输入框',
    icon: 'iconfont iconbiaodan',
    width: null,
    height: null,
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  },
  {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'textarea',
    title: '文本域',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '文本域',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'iconfont iconfuwenben',
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  },
  {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'password',
    title: '密码输入框',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '密码输入框',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'iconfont iconziyuan'
  }, {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'number',
    title: '数字输入框',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '数字输入框',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'iconfont iconshuzi',
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  },
  {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'date',
    title: '日期输入框',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '日期输入框',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'iconfont icontime',
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  },
  {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'time',
    title: '时间输入框',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '时间输入框',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'iconfont iconshijian',
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  },
  {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'select',
    title: '选择输入框',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '选择输入框',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'iconfont iconselect',
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  },
  {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'check',
    title: '复选框',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '复选框',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'iconfont iconfuxuankuang',
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  },
  {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'multiple',
    title: '多选框',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '多选框',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'iconfont iconcheckbox',
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  },
  {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'hide',
    title: '隐藏',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '隐藏',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'iconfont iconyincang',
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  },
  {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'picture',
    title: '图片',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '图片',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'iconfont icontupian',
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  },
  {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'file',
    title: '文件上传',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '文件上传',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'iconfont iconwenjianshangchuan',
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  },
  {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'column',
    title: '表格行号',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '表格行号',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'iconfont icon1',
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  }, {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'button',
    title: '按钮',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '按钮',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'iconfont iconButton',
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  }, {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'tag',
    title: '标签',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '标签',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'iconfont iconbiaoqian',
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  }, {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'show',
    title: '显示框',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '显示框',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'iconfont iconxianshi',
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  },
  {
    tb_window_formatsearch: [],
    asdatasource: false,
    isnullable: true,
    type: 'tb_window_element_actionColumn',
    title: '表格操作列',
    tb_window_inputfields: [],
    rowid: 0,
    tb_window_element_action: [],
    tb_window_selectfields: [],
    rightmargin: 0,
    readonly: false,
    authcontrol: false,
    istreecolumn: false,
    id: 0,
    tag: 0,
    mustsetfiltercon: false,
    createtime: 0,
    columnid: 0,
    editable: true,
    leftmargin: 0,
    topmargin: 0,
    tb_window_uploadfile: [],
    elementname: '',
    bottommargin: 0,
    astablevar: false,
    containerid: 0,
    updatetime: 0,
    searchop: 'eq',
    elementdesc: '',
    name: '表格操作列',
    objelement: '',
    labelwidth: 0,
    visible: '',
    elementstatus: '',
    defvalue: '',
    icon: 'el-icon-edit',
    displayformat: null,
    inputmask: null,
    emptytext: null,
    verifytype: null,
    verifyinfo: null,
    groupid: null,
    verifyformula: null
  }
]

export const containerFilter = [
  {
    'value': 'global',
    'label': '全局'
  },
  {
    'value': 'local',
    'label': '局部'
  },
  {
    'value': 'constant',
    'label': '常量'
  }
]
export const containerFilterWindow = [
  {
    'value': 'global',
    'label': '全局'
  },
  {
    'value': 'constant',
    'label': '常量'
  }
]
export const containerFilter2 = [
  {
    'value': 'global',
    'label': '全局'
  },
  {
    'value': 'local',
    'label': '局部'
  },
  {
    'value': 'constant',
    'label': '常量'
  }
]
export const tabInContainers = [
  {
    'label': 'FORM表单',
    'value': 'form'
  },
  {
    'label': '表格',
    'value': 'grid'
  },
  {
    'label': 'TAB页',
    'value': 'tabpanel'
  },
  {
    'label': 'CARD',
    'value': 'cardpanel'
  },
  {
    'label': '查询表单',
    'value': 'searchform'
  },
  {
    'label': '容器',
    'value': 'container'
  }
]
/**
 *
 * @param sourceObj
 * @param targetObj
 * @returns {string}
 */
export function activeColor (sourceObj, targetObj) {
  if (sourceObj != null && targetObj != null) {
    return sourceObj.id === targetObj.id ? '#7dbcea' : ''
  } else {
    return ''
  }
}

/**
 * 脚本类型下拉数据源
 * @type {*[]}
 */
export const elementTypes = [
  {
    'label': 'JS脚本',
    'value': 'js',
    'type': 'js'
  },
  {
    'label': 'SQL脚本',
    'value': 'sql',
    'type': 'db'
  },
  {
    'label': 'API+SQL脚本',
    'value': 'apiSql',
    'type': 'api'
  },
  {
    'label': 'API+参数脚本',
    'value': 'apiParams',
    'type': 'api'
  }
]

export const actions = [
  {
    'label': '新增对象',
    'value': 'AddObject'
  },
  {
    'label': '执行SQL',
    'value': 'ExecuteSql'
  }
]
